### ISSUE TITLE
[Balance]  Rubber Planks do not function as furnace fuel

### ISSUE THREAD

**Issue by MicahHaack** [ThePansmith/Break-the-barrier#10]
**Describe the issue**
Rubber wood planks do not have a burn time.

**Suggestion to fix**
Add a standard burn time to rubber wood planks.

**Screenshots**
![image](https://user-images.githubusercontent.com/44842363/154345138-2a37d210-8ce5-4369-b7c0-c11a31e1698e.png)

**Comment by htmlcsjs** [comment]
hmm this should probally go into [GregTechCEu/GregTech](https://github.com/GregTechCEu/GregTech)

**Comment by ThePansmith** [comment]
True, I'll whip up a fix for it when I get home, but this is mainly a ceu issue.

**Comment by MicahHaack** [comment]
I put in a feature suggestion on CEu

**Comment by ThePansmith** [comment]
Fixed with 1ac8846d85c0077f393305d03b5825977e8acd66
